#!/bin/sh

########################################################################
# Check that all Go files have been gofmt'd.
########################################################################
# Find all change go files.
gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')

./check-gofmt.sh $gofiles
./check-golint.sh

########################################################################
# Precommit hook to rebuild generated go code. Fails if building or
# copying the files fails.
########################################################################
bazelisk build //go/api/command:command_go_proto //go/api/fakes:auxiliary_metadata_go_proto
GEN_CMD_PATHS=("go/api/command/command.pb.go" "go/api/fakes/auxiliary_metadata.pb.go")
for path in "${GEN_CMD_PATHS[@]}"; do
    echo $path "$(find $(bazelisk info bazel-bin) -path "*/${path}")"
    cp -f "$(find $(bazelisk info bazel-bin) -path "*/${path}")" "${path}"
    git add "${path}"
done
