// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go/api/command/command.proto

package cmd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InputType_Value int32

const (
	InputType_UNSPECIFIED InputType_Value = 0
	InputType_DIRECTORY   InputType_Value = 1
	InputType_FILE        InputType_Value = 2
)

var InputType_Value_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "DIRECTORY",
	2: "FILE",
}

var InputType_Value_value = map[string]int32{
	"UNSPECIFIED": 0,
	"DIRECTORY":   1,
	"FILE":        2,
}

func (x InputType_Value) String() string {
	return proto.EnumName(InputType_Value_name, int32(x))
}

func (InputType_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{2, 0}
}

type CommandResultStatus_Value int32

const (
	CommandResultStatus_UNKNOWN       CommandResultStatus_Value = 0
	CommandResultStatus_SUCCESS       CommandResultStatus_Value = 1
	CommandResultStatus_CACHE_HIT     CommandResultStatus_Value = 2
	CommandResultStatus_NON_ZERO_EXIT CommandResultStatus_Value = 3
	CommandResultStatus_TIMEOUT       CommandResultStatus_Value = 4
	CommandResultStatus_INTERRUPTED   CommandResultStatus_Value = 5
	CommandResultStatus_REMOTE_ERROR  CommandResultStatus_Value = 6
	CommandResultStatus_LOCAL_ERROR   CommandResultStatus_Value = 7
)

var CommandResultStatus_Value_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "CACHE_HIT",
	3: "NON_ZERO_EXIT",
	4: "TIMEOUT",
	5: "INTERRUPTED",
	6: "REMOTE_ERROR",
	7: "LOCAL_ERROR",
}

var CommandResultStatus_Value_value = map[string]int32{
	"UNKNOWN":       0,
	"SUCCESS":       1,
	"CACHE_HIT":     2,
	"NON_ZERO_EXIT": 3,
	"TIMEOUT":       4,
	"INTERRUPTED":   5,
	"REMOTE_ERROR":  6,
	"LOCAL_ERROR":   7,
}

func (x CommandResultStatus_Value) String() string {
	return proto.EnumName(CommandResultStatus_Value_name, int32(x))
}

func (CommandResultStatus_Value) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{7, 0}
}

type Command struct {
	Identifiers          *Identifiers      `protobuf:"bytes,1,opt,name=identifiers,proto3" json:"identifiers,omitempty"`
	ExecRoot             string            `protobuf:"bytes,2,opt,name=exec_root,json=execRoot,proto3" json:"exec_root,omitempty"`
	Input                *InputSpec        `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Output               *OutputSpec       `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Args                 []string          `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	ExecutionTimeout     int32             `protobuf:"varint,6,opt,name=execution_timeout,json=executionTimeout,proto3" json:"execution_timeout,omitempty"`
	WorkingDirectory     string            `protobuf:"bytes,7,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	Platform             map[string]string `protobuf:"bytes,8,rep,name=platform,proto3" json:"platform,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetIdentifiers() *Identifiers {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *Command) GetExecRoot() string {
	if m != nil {
		return m.ExecRoot
	}
	return ""
}

func (m *Command) GetInput() *InputSpec {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Command) GetOutput() *OutputSpec {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *Command) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Command) GetExecutionTimeout() int32 {
	if m != nil {
		return m.ExecutionTimeout
	}
	return 0
}

func (m *Command) GetWorkingDirectory() string {
	if m != nil {
		return m.WorkingDirectory
	}
	return ""
}

func (m *Command) GetPlatform() map[string]string {
	if m != nil {
		return m.Platform
	}
	return nil
}

type Identifiers struct {
	CommandId               string   `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	InvocationId            string   `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	CorrelatedInvocationsId string   `protobuf:"bytes,3,opt,name=correlated_invocations_id,json=correlatedInvocationsId,proto3" json:"correlated_invocations_id,omitempty"`
	ToolName                string   `protobuf:"bytes,4,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolVersion             string   `protobuf:"bytes,5,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Identifiers) Reset()         { *m = Identifiers{} }
func (m *Identifiers) String() string { return proto.CompactTextString(m) }
func (*Identifiers) ProtoMessage()    {}
func (*Identifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{1}
}

func (m *Identifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifiers.Unmarshal(m, b)
}
func (m *Identifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifiers.Marshal(b, m, deterministic)
}
func (m *Identifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifiers.Merge(m, src)
}
func (m *Identifiers) XXX_Size() int {
	return xxx_messageInfo_Identifiers.Size(m)
}
func (m *Identifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifiers.DiscardUnknown(m)
}

var xxx_messageInfo_Identifiers proto.InternalMessageInfo

func (m *Identifiers) GetCommandId() string {
	if m != nil {
		return m.CommandId
	}
	return ""
}

func (m *Identifiers) GetInvocationId() string {
	if m != nil {
		return m.InvocationId
	}
	return ""
}

func (m *Identifiers) GetCorrelatedInvocationsId() string {
	if m != nil {
		return m.CorrelatedInvocationsId
	}
	return ""
}

func (m *Identifiers) GetToolName() string {
	if m != nil {
		return m.ToolName
	}
	return ""
}

func (m *Identifiers) GetToolVersion() string {
	if m != nil {
		return m.ToolVersion
	}
	return ""
}

type InputType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputType) Reset()         { *m = InputType{} }
func (m *InputType) String() string { return proto.CompactTextString(m) }
func (*InputType) ProtoMessage()    {}
func (*InputType) Descriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{2}
}

func (m *InputType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputType.Unmarshal(m, b)
}
func (m *InputType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputType.Marshal(b, m, deterministic)
}
func (m *InputType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputType.Merge(m, src)
}
func (m *InputType) XXX_Size() int {
	return xxx_messageInfo_InputType.Size(m)
}
func (m *InputType) XXX_DiscardUnknown() {
	xxx_messageInfo_InputType.DiscardUnknown(m)
}

var xxx_messageInfo_InputType proto.InternalMessageInfo

type ExcludeInput struct {
	Regex                string          `protobuf:"bytes,1,opt,name=regex,proto3" json:"regex,omitempty"`
	Type                 InputType_Value `protobuf:"varint,2,opt,name=type,proto3,enum=cmd.InputType_Value" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExcludeInput) Reset()         { *m = ExcludeInput{} }
func (m *ExcludeInput) String() string { return proto.CompactTextString(m) }
func (*ExcludeInput) ProtoMessage()    {}
func (*ExcludeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{3}
}

func (m *ExcludeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExcludeInput.Unmarshal(m, b)
}
func (m *ExcludeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExcludeInput.Marshal(b, m, deterministic)
}
func (m *ExcludeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExcludeInput.Merge(m, src)
}
func (m *ExcludeInput) XXX_Size() int {
	return xxx_messageInfo_ExcludeInput.Size(m)
}
func (m *ExcludeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ExcludeInput.DiscardUnknown(m)
}

var xxx_messageInfo_ExcludeInput proto.InternalMessageInfo

func (m *ExcludeInput) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

func (m *ExcludeInput) GetType() InputType_Value {
	if m != nil {
		return m.Type
	}
	return InputType_UNSPECIFIED
}

type VirtualInput struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Contents             []byte   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	IsExecutable         bool     `protobuf:"varint,3,opt,name=is_executable,json=isExecutable,proto3" json:"is_executable,omitempty"`
	IsEmptyDirectory     bool     `protobuf:"varint,4,opt,name=is_empty_directory,json=isEmptyDirectory,proto3" json:"is_empty_directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtualInput) Reset()         { *m = VirtualInput{} }
func (m *VirtualInput) String() string { return proto.CompactTextString(m) }
func (*VirtualInput) ProtoMessage()    {}
func (*VirtualInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{4}
}

func (m *VirtualInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualInput.Unmarshal(m, b)
}
func (m *VirtualInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualInput.Marshal(b, m, deterministic)
}
func (m *VirtualInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualInput.Merge(m, src)
}
func (m *VirtualInput) XXX_Size() int {
	return xxx_messageInfo_VirtualInput.Size(m)
}
func (m *VirtualInput) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualInput.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualInput proto.InternalMessageInfo

func (m *VirtualInput) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *VirtualInput) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *VirtualInput) GetIsExecutable() bool {
	if m != nil {
		return m.IsExecutable
	}
	return false
}

func (m *VirtualInput) GetIsEmptyDirectory() bool {
	if m != nil {
		return m.IsEmptyDirectory
	}
	return false
}

type InputSpec struct {
	Inputs               []string          `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	VirtualInputs        []*VirtualInput   `protobuf:"bytes,5,rep,name=virtual_inputs,json=virtualInputs,proto3" json:"virtual_inputs,omitempty"`
	ExcludeInputs        []*ExcludeInput   `protobuf:"bytes,3,rep,name=exclude_inputs,json=excludeInputs,proto3" json:"exclude_inputs,omitempty"`
	EnvironmentVariables map[string]string `protobuf:"bytes,4,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InputSpec) Reset()         { *m = InputSpec{} }
func (m *InputSpec) String() string { return proto.CompactTextString(m) }
func (*InputSpec) ProtoMessage()    {}
func (*InputSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{5}
}

func (m *InputSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputSpec.Unmarshal(m, b)
}
func (m *InputSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputSpec.Marshal(b, m, deterministic)
}
func (m *InputSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputSpec.Merge(m, src)
}
func (m *InputSpec) XXX_Size() int {
	return xxx_messageInfo_InputSpec.Size(m)
}
func (m *InputSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_InputSpec.DiscardUnknown(m)
}

var xxx_messageInfo_InputSpec proto.InternalMessageInfo

func (m *InputSpec) GetInputs() []string {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *InputSpec) GetVirtualInputs() []*VirtualInput {
	if m != nil {
		return m.VirtualInputs
	}
	return nil
}

func (m *InputSpec) GetExcludeInputs() []*ExcludeInput {
	if m != nil {
		return m.ExcludeInputs
	}
	return nil
}

func (m *InputSpec) GetEnvironmentVariables() map[string]string {
	if m != nil {
		return m.EnvironmentVariables
	}
	return nil
}

type OutputSpec struct {
	OutputFiles          []string `protobuf:"bytes,1,rep,name=output_files,json=outputFiles,proto3" json:"output_files,omitempty"`
	OutputDirectories    []string `protobuf:"bytes,2,rep,name=output_directories,json=outputDirectories,proto3" json:"output_directories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputSpec) Reset()         { *m = OutputSpec{} }
func (m *OutputSpec) String() string { return proto.CompactTextString(m) }
func (*OutputSpec) ProtoMessage()    {}
func (*OutputSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{6}
}

func (m *OutputSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputSpec.Unmarshal(m, b)
}
func (m *OutputSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputSpec.Marshal(b, m, deterministic)
}
func (m *OutputSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputSpec.Merge(m, src)
}
func (m *OutputSpec) XXX_Size() int {
	return xxx_messageInfo_OutputSpec.Size(m)
}
func (m *OutputSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputSpec.DiscardUnknown(m)
}

var xxx_messageInfo_OutputSpec proto.InternalMessageInfo

func (m *OutputSpec) GetOutputFiles() []string {
	if m != nil {
		return m.OutputFiles
	}
	return nil
}

func (m *OutputSpec) GetOutputDirectories() []string {
	if m != nil {
		return m.OutputDirectories
	}
	return nil
}

type CommandResultStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandResultStatus) Reset()         { *m = CommandResultStatus{} }
func (m *CommandResultStatus) String() string { return proto.CompactTextString(m) }
func (*CommandResultStatus) ProtoMessage()    {}
func (*CommandResultStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{7}
}

func (m *CommandResultStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResultStatus.Unmarshal(m, b)
}
func (m *CommandResultStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResultStatus.Marshal(b, m, deterministic)
}
func (m *CommandResultStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResultStatus.Merge(m, src)
}
func (m *CommandResultStatus) XXX_Size() int {
	return xxx_messageInfo_CommandResultStatus.Size(m)
}
func (m *CommandResultStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResultStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResultStatus proto.InternalMessageInfo

type CommandResult struct {
	Status               CommandResultStatus_Value `protobuf:"varint,1,opt,name=status,proto3,enum=cmd.CommandResultStatus_Value" json:"status,omitempty"`
	ExitCode             int32                     `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Msg                  string                    `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CommandResult) Reset()         { *m = CommandResult{} }
func (m *CommandResult) String() string { return proto.CompactTextString(m) }
func (*CommandResult) ProtoMessage()    {}
func (*CommandResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{8}
}

func (m *CommandResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResult.Unmarshal(m, b)
}
func (m *CommandResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResult.Marshal(b, m, deterministic)
}
func (m *CommandResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResult.Merge(m, src)
}
func (m *CommandResult) XXX_Size() int {
	return xxx_messageInfo_CommandResult.Size(m)
}
func (m *CommandResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResult.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResult proto.InternalMessageInfo

func (m *CommandResult) GetStatus() CommandResultStatus_Value {
	if m != nil {
		return m.Status
	}
	return CommandResultStatus_UNKNOWN
}

func (m *CommandResult) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *CommandResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TimeInterval struct {
	From                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeInterval) Reset()         { *m = TimeInterval{} }
func (m *TimeInterval) String() string { return proto.CompactTextString(m) }
func (*TimeInterval) ProtoMessage()    {}
func (*TimeInterval) Descriptor() ([]byte, []int) {
	return fileDescriptor_c902c8825c04350d, []int{9}
}

func (m *TimeInterval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeInterval.Unmarshal(m, b)
}
func (m *TimeInterval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeInterval.Marshal(b, m, deterministic)
}
func (m *TimeInterval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeInterval.Merge(m, src)
}
func (m *TimeInterval) XXX_Size() int {
	return xxx_messageInfo_TimeInterval.Size(m)
}
func (m *TimeInterval) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeInterval.DiscardUnknown(m)
}

var xxx_messageInfo_TimeInterval proto.InternalMessageInfo

func (m *TimeInterval) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TimeInterval) GetTo() *timestamp.Timestamp {
	if m != nil {
		return m.To
	}
	return nil
}

func init() {
	proto.RegisterEnum("cmd.InputType_Value", InputType_Value_name, InputType_Value_value)
	proto.RegisterEnum("cmd.CommandResultStatus_Value", CommandResultStatus_Value_name, CommandResultStatus_Value_value)
	proto.RegisterType((*Command)(nil), "cmd.Command")
	proto.RegisterMapType((map[string]string)(nil), "cmd.Command.PlatformEntry")
	proto.RegisterType((*Identifiers)(nil), "cmd.Identifiers")
	proto.RegisterType((*InputType)(nil), "cmd.InputType")
	proto.RegisterType((*ExcludeInput)(nil), "cmd.ExcludeInput")
	proto.RegisterType((*VirtualInput)(nil), "cmd.VirtualInput")
	proto.RegisterType((*InputSpec)(nil), "cmd.InputSpec")
	proto.RegisterMapType((map[string]string)(nil), "cmd.InputSpec.EnvironmentVariablesEntry")
	proto.RegisterType((*OutputSpec)(nil), "cmd.OutputSpec")
	proto.RegisterType((*CommandResultStatus)(nil), "cmd.CommandResultStatus")
	proto.RegisterType((*CommandResult)(nil), "cmd.CommandResult")
	proto.RegisterType((*TimeInterval)(nil), "cmd.TimeInterval")
}

func init() { proto.RegisterFile("go/api/command/command.proto", fileDescriptor_c902c8825c04350d) }

var fileDescriptor_c902c8825c04350d = []byte{
	// 949 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5b, 0x8f, 0xe3, 0x34,
	0x14, 0xde, 0xf4, 0x36, 0xed, 0x69, 0x3b, 0x9b, 0x31, 0x03, 0x74, 0xcb, 0xad, 0x04, 0x24, 0x2a,
	0x2e, 0x19, 0x51, 0xa4, 0xd5, 0x6a, 0x91, 0x90, 0x56, 0x6d, 0x86, 0x8d, 0x98, 0x6d, 0x47, 0x6e,
	0x3a, 0x5c, 0x24, 0x88, 0x32, 0x89, 0x5b, 0xcc, 0x26, 0x71, 0x94, 0x38, 0x65, 0xfa, 0xce, 0x23,
	0x2f, 0xbc, 0xf3, 0x5f, 0xf8, 0x05, 0xfc, 0x27, 0xe4, 0x4b, 0xdb, 0x8c, 0x04, 0x48, 0xfb, 0x94,
	0xf8, 0xfb, 0x3e, 0x1f, 0xdb, 0x9f, 0xcf, 0x39, 0x86, 0xb7, 0x37, 0xec, 0x22, 0xc8, 0xe8, 0x45,
	0xc8, 0x92, 0x24, 0x48, 0xa3, 0xfd, 0xd7, 0xce, 0x72, 0xc6, 0x19, 0xaa, 0x87, 0x49, 0x34, 0x7c,
	0x6f, 0xc3, 0xd8, 0x26, 0x26, 0x17, 0x12, 0xba, 0x2d, 0xd7, 0x17, 0x9c, 0x26, 0xa4, 0xe0, 0x41,
	0x92, 0x29, 0x95, 0xf5, 0x7b, 0x1d, 0x4e, 0xa6, 0x6a, 0x1e, 0x9a, 0x40, 0x97, 0x46, 0x24, 0xe5,
	0x74, 0x4d, 0x49, 0x5e, 0x0c, 0x8c, 0x91, 0x31, 0xee, 0x4e, 0x4c, 0x3b, 0x4c, 0x22, 0xdb, 0x3d,
	0xe2, 0xb8, 0x2a, 0x42, 0x6f, 0x41, 0x87, 0xdc, 0x91, 0xd0, 0xcf, 0x19, 0xe3, 0x83, 0xda, 0xc8,
	0x18, 0x77, 0x70, 0x5b, 0x00, 0x98, 0x31, 0x8e, 0x3e, 0x84, 0x26, 0x4d, 0xb3, 0x92, 0x0f, 0xea,
	0x32, 0xd4, 0xa9, 0x0a, 0x25, 0x90, 0x65, 0x46, 0x42, 0xac, 0x48, 0xf4, 0x11, 0xb4, 0x58, 0xc9,
	0x85, 0xac, 0x21, 0x65, 0x0f, 0xa5, 0x6c, 0x21, 0x21, 0xa9, 0xd3, 0x34, 0x42, 0xd0, 0x08, 0xf2,
	0x4d, 0x31, 0x68, 0x8e, 0xea, 0xe3, 0x0e, 0x96, 0xff, 0xe8, 0x13, 0x38, 0x13, 0xcb, 0x95, 0x9c,
	0xb2, 0xd4, 0x17, 0x87, 0x63, 0x25, 0x1f, 0xb4, 0x46, 0xc6, 0xb8, 0x89, 0xcd, 0x03, 0xe1, 0x29,
	0x5c, 0x88, 0x7f, 0x65, 0xf9, 0x4b, 0x9a, 0x6e, 0xfc, 0x88, 0xe6, 0x24, 0xe4, 0x2c, 0xdf, 0x0d,
	0x4e, 0xe4, 0xa6, 0x4d, 0x4d, 0xcc, 0xf6, 0x38, 0x7a, 0x0c, 0xed, 0x2c, 0x0e, 0xf8, 0x9a, 0xe5,
	0xc9, 0xa0, 0x3d, 0xaa, 0x8f, 0xbb, 0x93, 0xa1, 0xdc, 0x98, 0x76, 0xcb, 0xbe, 0xd6, 0xa4, 0x93,
	0xf2, 0x7c, 0x87, 0x0f, 0xda, 0xe1, 0x97, 0xd0, 0xbf, 0x47, 0x21, 0x13, 0xea, 0x2f, 0xc9, 0x4e,
	0xda, 0xd9, 0xc1, 0xe2, 0x17, 0x9d, 0x43, 0x73, 0x1b, 0xc4, 0x25, 0xd1, 0x86, 0xa9, 0xc1, 0xd3,
	0xda, 0x13, 0xc3, 0xfa, 0xdb, 0x80, 0x6e, 0xc5, 0x6b, 0xf4, 0x0e, 0x80, 0xbe, 0x55, 0x9f, 0x46,
	0x3a, 0x44, 0x47, 0x23, 0x6e, 0x84, 0x3e, 0x80, 0x3e, 0x4d, 0xb7, 0x2c, 0x0c, 0xe4, 0xf1, 0x69,
	0xa4, 0x03, 0xf6, 0x8e, 0xa0, 0x1b, 0xa1, 0xa7, 0xf0, 0x28, 0x64, 0x79, 0x4e, 0xe2, 0x80, 0x93,
	0xc8, 0x3f, 0x52, 0x85, 0x98, 0x50, 0x97, 0x13, 0xde, 0x3c, 0x0a, 0xdc, 0x23, 0xef, 0x46, 0xe2,
	0x7a, 0x39, 0x63, 0xb1, 0x9f, 0x06, 0x09, 0x91, 0xd7, 0xd3, 0xc1, 0x6d, 0x01, 0xcc, 0x83, 0x84,
	0xa0, 0xf7, 0xa1, 0x27, 0xc9, 0x2d, 0xc9, 0x0b, 0xca, 0xd2, 0x41, 0x53, 0xf2, 0x5d, 0x81, 0xdd,
	0x28, 0xc8, 0xfa, 0x0a, 0x3a, 0xf2, 0xbe, 0xbd, 0x5d, 0x46, 0xac, 0xcf, 0xa1, 0x79, 0x23, 0x4e,
	0x8a, 0x1e, 0x42, 0x77, 0x35, 0x5f, 0x5e, 0x3b, 0x53, 0xf7, 0xd2, 0x75, 0x66, 0xe6, 0x03, 0xd4,
	0x87, 0xce, 0xcc, 0xc5, 0xce, 0xd4, 0x5b, 0xe0, 0xef, 0x4d, 0x03, 0xb5, 0xa1, 0x71, 0xe9, 0x5e,
	0x39, 0x66, 0xcd, 0x9a, 0x43, 0xcf, 0xb9, 0x0b, 0xe3, 0x32, 0x22, 0x32, 0x8c, 0x70, 0x2e, 0x27,
	0x1b, 0x72, 0xa7, 0xad, 0x50, 0x03, 0x34, 0x86, 0x06, 0xdf, 0x65, 0xca, 0xce, 0xd3, 0xc9, 0xf9,
	0x31, 0xcd, 0xc4, 0xb2, 0xb6, 0x5c, 0x13, 0x4b, 0x85, 0xf5, 0x87, 0x01, 0xbd, 0x1b, 0x9a, 0xf3,
	0x32, 0x88, 0x55, 0x40, 0x04, 0x8d, 0x2c, 0xe0, 0x3f, 0xeb, 0x78, 0xf2, 0x1f, 0x0d, 0xa1, 0x1d,
	0xb2, 0x94, 0x93, 0x94, 0x17, 0x32, 0x64, 0x0f, 0x1f, 0xc6, 0xd2, 0xf1, 0xc2, 0x57, 0x99, 0x15,
	0xdc, 0xc6, 0x44, 0x1a, 0xd8, 0xc6, 0x3d, 0x5a, 0x38, 0x07, 0x0c, 0x7d, 0x0a, 0x48, 0x88, 0x92,
	0x8c, 0xef, 0x2a, 0x89, 0xd6, 0x90, 0x4a, 0x93, 0x16, 0x8e, 0x20, 0x0e, 0x89, 0x66, 0xfd, 0x55,
	0xd3, 0x26, 0x89, 0x64, 0x47, 0x6f, 0x40, 0x4b, 0x96, 0x85, 0x58, 0x5a, 0xa4, 0xb9, 0x1e, 0xa1,
	0x27, 0x70, 0xba, 0x55, 0x1b, 0xf7, 0x35, 0xdf, 0x94, 0x49, 0x79, 0x26, 0x4f, 0x5b, 0x3d, 0x13,
	0xee, 0x6f, 0x2b, 0x23, 0x39, 0x93, 0x28, 0x0f, 0xf7, 0x33, 0xeb, 0x95, 0x99, 0x55, 0x7b, 0x71,
	0x9f, 0x54, 0x46, 0x05, 0xfa, 0x11, 0x5e, 0x27, 0xe9, 0x96, 0xe6, 0x2c, 0x4d, 0x48, 0xca, 0xfd,
	0x6d, 0x90, 0x53, 0x71, 0xbe, 0x62, 0xd0, 0x90, 0x01, 0xc6, 0xf7, 0xeb, 0xd9, 0x76, 0x8e, 0xda,
	0x9b, 0xbd, 0x54, 0x55, 0xc7, 0x39, 0xf9, 0x17, 0x6a, 0xf8, 0x35, 0x3c, 0xfa, 0xcf, 0x29, 0xaf,
	0x54, 0x35, 0x3f, 0x01, 0x1c, 0xdb, 0x85, 0x48, 0x4b, 0xd5, 0x30, 0xfc, 0x35, 0x15, 0x9b, 0x35,
	0xa4, 0x8f, 0x5d, 0x85, 0x5d, 0x0a, 0x08, 0x7d, 0x06, 0x48, 0x4b, 0xf6, 0xd7, 0x43, 0xc9, 0xde,
	0xf0, 0x33, 0xc5, 0xcc, 0x8e, 0x84, 0xf5, 0xa7, 0x01, 0xaf, 0xe9, 0xb2, 0xc7, 0xa4, 0x28, 0x63,
	0xbe, 0xe4, 0x01, 0x2f, 0x0b, 0xeb, 0x37, 0x63, 0x9f, 0xd1, 0x5d, 0x38, 0x59, 0xcd, 0xbf, 0x99,
	0x2f, 0xbe, 0x9d, 0x9b, 0x0f, 0xc4, 0x60, 0xb9, 0x9a, 0x4e, 0x9d, 0xe5, 0xd2, 0x34, 0x44, 0x6a,
	0x4f, 0x9f, 0x4d, 0x9f, 0x3b, 0xfe, 0x73, 0xd7, 0x33, 0x6b, 0xe8, 0x0c, 0xfa, 0xf3, 0xc5, 0xdc,
	0xff, 0xc1, 0xc1, 0x0b, 0xdf, 0xf9, 0xce, 0xf5, 0xcc, 0xba, 0x90, 0x7b, 0xee, 0x0b, 0x67, 0xb1,
	0xf2, 0xcc, 0x86, 0x28, 0x0d, 0x77, 0xee, 0x39, 0x18, 0xaf, 0xae, 0x3d, 0x67, 0x66, 0x36, 0x91,
	0x09, 0x3d, 0xec, 0xbc, 0x58, 0x78, 0x8e, 0xef, 0x60, 0xbc, 0xc0, 0x66, 0x4b, 0x48, 0xae, 0x16,
	0xd3, 0x67, 0x57, 0x1a, 0x38, 0xb1, 0xb6, 0xd0, 0xbf, 0xb7, 0x3b, 0xf4, 0x18, 0x5a, 0x85, 0xdc,
	0xa1, 0xb4, 0xef, 0x74, 0xf2, 0x6e, 0xb5, 0x71, 0x55, 0x4f, 0xa0, 0x6b, 0x43, 0xab, 0x55, 0x33,
	0xa7, 0xdc, 0x0f, 0x59, 0xa4, 0x5c, 0x6e, 0x8a, 0x66, 0x4e, 0xf9, 0x94, 0x45, 0x44, 0x5c, 0x48,
	0x52, 0x6c, 0x74, 0xc3, 0x10, 0xbf, 0xd6, 0x2f, 0xd0, 0x13, 0x9d, 0xd5, 0x4d, 0x39, 0xc9, 0xb7,
	0x41, 0x8c, 0x6c, 0x68, 0xac, 0x73, 0x96, 0xe8, 0x87, 0x63, 0x68, 0xab, 0xb7, 0xc7, 0xde, 0xbf,
	0x3d, 0xb6, 0xb7, 0x7f, 0x7b, 0xb0, 0xd4, 0xa1, 0x8f, 0xa1, 0xc6, 0x99, 0x5c, 0xe7, 0xff, 0xd5,
	0x35, 0xce, 0x6e, 0x5b, 0x12, 0xff, 0xe2, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x60, 0xd1, 0x21,
	0xd1, 0xf4, 0x06, 0x00, 0x00,
}
